### ISSUE TITLE
失效了

### ISSUE THREAD

**Issue by binlidaily** [h3l/douban-workflow#1]
rt

**Comment by h3l** [comment]
emmm 我一直在用都是 OK 的，可以把日志贴上来么？

**Comment by binlidaily** [comment]
您可以看下 book 的搜索，应该是豆瓣把 book 的 api 禁掉了？

**Comment by h3l** [comment]
![image](https://user-images.githubusercontent.com/1664952/55702685-ea159800-5a09-11e9-9123-b90065cc8e8c.png)
没问题的，而且我这边也没用 book 的 api，你安装好试试`dbb 算法导论`试试

**Comment by binlidaily** [comment]
![image](https://user-images.githubusercontent.com/5987437/55703792-2991b380-5a0d-11e9-99c6-83bab218391d.png)

**Comment by h3l** [comment]
不好意思 看起来是依赖关系处理的有点问题 我这几天拿 go 重构一遍 好了我这边 @ 你之后在 close 这个 issue

**Comment by h3l** [comment]
@binlidaily 可以使用了，重新下载就好，这个 issue 我关了，有问题随时再开，

**Comment by liyang85** [comment]
似乎又失效了，请开发者帮忙检查一下，谢谢。

<img width="1018" alt="Xnip2020-12-26_19-05-07" src="https://user-images.githubusercontent.com/20695423/103150349-4c9a6300-47ae-11eb-8a91-81f64d76dc40.png">

<img width="1009" alt="Xnip2020-12-26_19-10-28" src="https://user-images.githubusercontent.com/20695423/103150348-4c01cc80-47ae-11eb-8c30-c68457c7ee4b.png">

<img width="1011" alt="Xnip2020-12-26_19-11-16" src="https://user-images.githubusercontent.com/20695423/103150346-499f7280-47ae-11eb-8596-348d1c00ca26.png">
