### ISSUE TITLE
你好，能否在展示的时候带上作者名字

### ISSUE THREAD

**Issue by howie6879** [h3l/douban-workflow#3]
![image](https://user-images.githubusercontent.com/17047388/87524472-cafcc000-c6ba-11ea-8606-617fe4d7fabe.png)
你好，能否在展示的时候带上作者名字

**Comment by muyinliu** [comment]
这个扩展用到的是 `https://m.douban.com/search/?query=<searchword>&type=<type>`，只提供名称和评分，没有更多的相关信息，没办法...

**Comment by howie6879** [comment]
请问为什么不用这个？https://search.douban.com/book/subject_search?search_text=

**Comment by muyinliu** [comment]
> 请问为什么不用这个？https://search.douban.com/book/subject_search?search_text=

因为这个 API 返回的 HTML 里面名称和评分等信息是加密的（你可以自己用 `curl` 获取一下 HTML 就能看出来），必须执行页面的 JavaScript 才能解密，你可以试着用 [nightmare](https://github.com/segmentio/nightmare) 之类的 Scriptable 的工具来实现，可以参考这个 bash script（要自己用 `brew install pup jq` 安装 `pup` `jq`，还要用 `npm install -g nightmare` 安装 `nightmare`）:

```shell
function urlencode () {
    if [ -z "$1" ]; then
        # read only 1 line from STDIN without EOF
        python -c "import sys, urllib as ul; print ul.quote_plus(sys.stdin.readline()[:-1])"
    else
        # use parameter
        python -c "import sys, urllib as ul; print ul.quote_plus(\"$1\")"
    fi;
}

function book () {
    echo "$1" | urlencode \
              | xargs -I NAME \
                  node -e "const Nightmare = require('nightmare'); const nightmare = new Nightmare(); nightmare.goto(process.argv[1]).wait('.item-root').evaluate(() => {return document.body.outerHTML;}).end().then(body_html => {console.log(body_html);});" \
                       "https://search.douban.com/book/subject_search?search_text=NAME&cat=1001" \
              | pup '.item-root json{}' \
              | jq 'map(select(.children[1].children[0].children[0].text != null)) | map({"title": .children[1].children[0].children[0].text, "rating": .children[1].children[1].children[1].text, "meta_abstract": .children[1].children[2].text, "url": .children[1].children[0].children[0].href, "image": .children[0].children[0].src})'
}
```

命令 `book 深度学习` 返回的是：

<img width="703" alt="QQ20200817-171821@2x" src="https://user-images.githubusercontent.com/3318872/90379740-b04cab00-e0ad-11ea-8dae-4fa11e968c08.png">

**Comment by howie6879** [comment]
明白了哈，辛苦辛苦
